"""Tabelas de referência globais (nacionalidade, raça, etnia, logradouro)

Revision ID: 0012_reference_tables
Revises: 0011_sigtap_tables
Create Date: 2026-04-16

Dados de cadastro compartilhados entre todos os municípios. Códigos seguem
o padrão DATASUS/e-SUS (idNacionalidade, idRaca, idLogradouro, idEtnia).

Todas as tabelas têm:
- id (UUID v7)
- codigo (código oficial DATASUS — string)
- descricao (nome apresentado)
- is_system (bool — true = oficial DATASUS, não editável pelo MASTER)
- active (bool — MASTER pode desativar, mesmo se for oficial)
- created_at / updated_at
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.types import UUIDType
revision: str = "0012_reference_tables"
down_revision: str | None = "0011_sigtap_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ══════════════════════════════════════════════════════════════════════════════
# Seeds (mantidos em Python pra ficar versionado; dados oficiais do DATASUS)
# ══════════════════════════════════════════════════════════════════════════════

NACIONALIDADES: list[tuple[str, str]] = [
    ("10", "BRASIL"),
    ("20", "RESERVADO"),
    ("21", "ARGENTINA"),
    ("22", "BOLIVIA"),
    ("23", "CHILE"),
    ("24", "PARAGUAI"),
    ("25", "URUGUAI"),
    ("26", "COLOMBIA"),
    ("27", "EQUADOR"),
    ("28", "ANTIGUA E. DEP. BARBUDA"),
    ("29", "ANTILHAS HOLANDESAS"),
    ("30", "ALEMANHA"),
    ("31", "BELGICA"),
    ("32", "GRA-BRETANHA"),
    ("33", "ARUBA"),
    ("34", "CANADA"),
    ("35", "ESPANHA"),
    ("36", "ESTADOS UNIDOS DA AMERICA (EUA)"),
    ("37", "FRANCA"),
    ("38", "SUICA"),
    ("39", "ITALIA"),
    ("40", "COMUNIDADE DAS BAHAMAS"),
    ("41", "JAPAO"),
    ("42", "CHINA"),
    ("43", "COREIA"),
    ("44", "BARBADOS"),
    ("45", "PORTUGAL"),
    ("46", "BELIZE"),
    ("47", "ILHAS TURKS E CAICOS"),
    ("48", "RESERVADO"),
    ("49", "RESERVADO"),
    ("50", "RESERVADO"),
    ("51", "COSTA RICA"),
    ("52", "CUBA"),
    ("53", "CURACAO"),
    ("54", "COMUNIDADE DOMINICANA"),
    ("55", "REPUBLICA DOMINICANA"),
    ("56", "REPUBLICA DE EL SALVADOR"),
    ("57", "ESTADOS ASSOC. DAS ANTILHAS"),
    ("58", "ILHAS FALKLANDS"),
    ("59", "GRANADA"),
    ("60", "ILHAS GUADALUPE"),
    ("61", "GUATEMALA"),
    ("62", "REPUBLICA DO HAITI"),
    ("63", "HONDURAS BRITANICAS"),
    ("64", "HONDURAS"),
    ("65", "ILHAS SERRANAS"),
    ("66", "JAMAICA"),
    ("67", "ILHAS MALVINAS"),
    ("68", "MARTINICA"),
    ("69", "ILHA MILHOS"),
    ("70", "MONTE SERRAT"),
    ("71", "NICARAGUA"),
    ("72", "PANAMA"),
    ("73", "PANAMA(ZONA DO CANAL)"),
    ("74", "PORTO RICO"),
    ("75", "QUITASUENO"),
    ("76", "RONCADOR"),
    ("77", "SANTA LUCIA"),
    ("78", "SAO CRISTOVAO"),
    ("79", "SAO VICENTE"),
    ("80", "ILHAS TURCA"),
    ("81", "ILHAS VIRGENS BRITANICAS"),
    ("82", "ILHAS VIRGENS AMERICANAS"),
    ("83", "BERMUDAS"),
    ("84", "GROENLANDIA"),
    ("85", "MEXICO"),
    ("86", "ST. PIERRE ET MIQUELON"),
    ("87", "GUIANA FRANCESA"),
    ("88", "REPUBLICA GUIANA"),
    ("89", "PERU"),
    ("90", "SURINAME"),
    ("91", "TRINIDAD E TOBAGO"),
    ("92", "VENEZUELA"),
    ("93", "ALBANIA"),
    ("94", "ANDORRA"),
    ("95", "AUSTRIA"),
    ("96", "BULGARIA"),
    ("97", "CHIPRE"),
    ("98", "DINAMARCA"),
    ("99", "EIRE"),
    ("100", "ESCOCIA"),
    ("101", "ILHAS FAROES"),
    ("102", "FINLANDIA"),
    ("103", "GIBRALTAR"),
    ("104", "GRECIA"),
    ("105", "HOLANDA"),
    ("106", "HUNGRIA"),
    ("107", "ILHAS BALEARES"),
    ("108", "ILHAS COSMOLEDO (LOMORES)"),
    ("109", "ILHAS DO CANAL"),
    ("110", "INGLATERRA"),
    ("111", "IRLANDA DO NORTE"),
    ("112", "IRLANDA"),
    ("113", "ISLANDIA"),
    ("114", "IUGOSLAVIA"),
    ("115", "LIECHTENSTEIN"),
    ("116", "LUXEMBURGO"),
    ("117", "ILHAS DE MAN"),
    ("118", "MONACO"),
    ("119", "NORUEGA"),
    ("120", "REPUBLICA DE MALTA"),
    ("121", "PAIS DE GALES"),
    ("122", "PAISES BAIXOS"),
    ("123", "POLONIA"),
    ("124", "ROMENIA"),
    ("125", "SAN MARINO"),
    ("126", "SUECIA"),
    ("127", "SVALBARD E JAN MAYER,IS"),
    ("128", "TCHECOSLOVAQUIA"),
    ("129", "ESTADO DA CIDADE DO VATICANO"),
    ("130", "CROACIA"),
    ("131", "SERVIA"),
    ("132", "ESLOVENIA"),
    ("133", "REPUBLICA DA MACEDONIA"),
    ("134", "BOSNIA HERZEGOVINA"),
    ("135", "REPUBLICA TCHECA"),
    ("136", "ESLOVAQUIA"),
    ("137", "MONTENEGRO"),
    ("138", "AZERBAIJAO"),
    ("139", "BASHKISTA"),
    ("140", "REPUBLICA DA BIELORRUSSIA"),
    ("141", "BURYAT"),
    ("142", "CARELIA"),
    ("143", "CAZAQUISTAO"),
    ("144", "CHECHEN INGUSTH"),
    ("145", "CHUVASH"),
    ("146", "DAGESTA"),
    ("147", "ESTONIA"),
    ("148", "GEORGIA"),
    ("149", "GORNO ALTAI"),
    ("150", "KABARDINO BALKAR"),
    ("151", "KALMIR"),
    ("152", "KARACHAEVOCHERKESS"),
    ("153", "KHAKASS"),
    ("154", "KOMI"),
    ("155", "LETONIA"),
    ("156", "LITUANIA"),
    ("157", "MARI"),
    ("158", "MOLDAVIA"),
    ("159", "OSSETIA SETENTRIONAL"),
    ("160", "QUIRGUISTAO"),
    ("161", "TADJIQUISTAO"),
    ("162", "TARTARIA"),
    ("163", "TURCOMENISTAO"),
    ("164", "TUVIN"),
    ("165", "UCRANIA"),
    ("166", "UDMURT"),
    ("167", "UNIAO SOVIETICA"),
    ("168", "UZBEQUISTAO"),
    ("169", "YAKUT"),
    ("170", "ABISSINIA"),
    ("171", "ACORES"),
    ("172", "AFAR FRANCES"),
    ("173", "REPUBLICA DA AFRICA DO SUL"),
    ("174", "ALTO VOLTA"),
    ("175", "ANGOLA"),
    ("176", "ARGELIA"),
    ("177", "BECHUANALANDIA"),
    ("178", "BENIN"),
    ("179", "BOTSUANA"),
    ("180", "BURUNDI"),
    ("181", "CAMAROES"),
    ("182", "CEUTA E MELILLA"),
    ("183", "CHADE"),
    ("184", "ILHAS COMORES"),
    ("185", "CONGO"),
    ("186", "COSTA DO MARFIM"),
    ("187", "DAOME"),
    ("188", "DJIBUTI"),
    ("189", "REPUBLICA ARABE DO EGITO"),
    ("190", "ETIOPIA"),
    ("191", "REPUBLICA DO GABAO"),
    ("192", "GAMBIA"),
    ("193", "GANA"),
    ("194", "GAZA"),
    ("195", "GUINE"),
    ("196", "GUINE EQUATORIAL"),
    ("197", "IFNI"),
    ("198", "ASCENSAO E TRISTAO DA CUNHA,IS"),
    ("199", "ILHAS CANARIAS"),
    ("200", "LESOTO"),
    ("201", "LIBERIA"),
    ("202", "LIBIA"),
    ("203", "MADEIRA"),
    ("204", "MALAWI"),
    ("205", "MADAGASCAR"),
    ("206", "MALI"),
    ("207", "MARROCOS"),
    ("208", "MAURICIO"),
    ("209", "MAURITANIA"),
    ("210", "MOCAMBIQUE"),
    ("211", "NGUANE"),
    ("212", "REPUBLICA DO NIGER"),
    ("213", "NIGERIA"),
    ("214", "PAPUA NOVA GUINE"),
    ("215", "PRACAS NORTE AFRICANAS"),
    ("216", "PROTETOR DO SUDOESTE AFRICANO"),
    ("217", "QUENIA"),
    ("218", "REPUBLICA CENTRO AFRICANA"),
    ("219", "REUNIAO"),
    ("220", "RODESIA (ZIMBABWE)"),
    ("221", "RUANDA"),
    ("222", "SAARA ESPANHOL"),
    ("223", "SANTA HELENA"),
    ("224", "SAO TOME E PRINCIPE"),
    ("225", "SEYCHELLES"),
    ("226", "SERRA LEOA"),
    ("227", "SOMALIA, REPUBLICA"),
    ("228", "SUAZILANDIA"),
    ("229", "SUDAO"),
    ("230", "TANGANICA"),
    ("231", "TERRIT. BRITANICO DO OCEANO INDICO"),
    ("232", "TRANSKEI"),
    ("233", "TOGO"),
    ("234", "TUNISIA"),
    ("235", "UGANDA"),
    ("236", "ZAIRE"),
    ("237", "ZAMBIA"),
    ("238", "BURKINA FASSO"),
    ("239", "ZIMBABWE"),
    ("240", "NAMIBIA"),
    ("241", "AFEGANISTAO"),
    ("242", "ARABIA SAUDITA"),
    ("243", "BAHREIN"),
    ("244", "BIRMANIA"),
    ("245", "BRUNEI"),
    ("246", "BHUTAN"),
    ("247", "CATAR"),
    ("248", "CEILAO"),
    ("249", "CHINA (TAIWAN)"),
    ("250", "COVEITE"),
    ("251", "EMIRADOS ARABES UNIDOS"),
    ("252", "FILIPINAS"),
    ("253", "HONG-KONG"),
    ("254", "IEMEN"),
    ("255", "INDIA"),
    ("256", "INDONESIA"),
    ("257", "IRA"),
    ("258", "IRAQUE"),
    ("259", "ISRAEL"),
    ("260", "JORDANIA"),
    ("261", "KMER/CAMBOJA"),
    ("262", "KUWAIT"),
    ("263", "LAOS"),
    ("264", "LIBANO"),
    ("265", "MACAU"),
    ("266", "MALASIA"),
    ("267", "MALDIVAS,IS"),
    ("268", "MASCATE"),
    ("269", "MONGOLIA"),
    ("270", "NEPAL"),
    ("271", "OMAN"),
    ("272", "PALESTINA"),
    ("273", "PAQUISTAO"),
    ("274", "RUIQUIU,IS"),
    ("275", "CINGAPURA"),
    ("276", "SEQUIN"),
    ("277", "SIRIA"),
    ("278", "SRI-LANKA"),
    ("279", "TAILANDIA"),
    ("280", "TREGUA, ESTADO"),
    ("281", "TURQUIA"),
    ("282", "VIETNA DO NORTE"),
    ("283", "VIETNA DO SUL"),
    ("284", "MIANMA"),
    ("285", "ARQUIPELAGO MANAHIKI"),
    ("286", "ARQUIPELAGO MIDWAY"),
    ("287", "ASHMORE E CARTIER"),
    ("288", "AUSTRALIA"),
    ("289", "ARQUIPELAGO DE BISMARK"),
    ("290", "ILHAS COOK"),
    ("291", "REPUBLICA DE FIJI"),
    ("292", "GUAM"),
    ("293", "ILHAS BAKER"),
    ("294", "ILHAS CANTAO E ENDERBURG"),
    ("295", "ILHAS CAROLINAS"),
    ("296", "ILHAS DO PACIFICO"),
    ("297", "ILHAS CHRISTMAS"),
    ("298", "ILHAS GILBERT"),
    ("299", "ILHAS HOWLAND E JARVIS"),
    ("300", "ILHA JOHNSTON E SAND"),
    ("301", "ILHAS KINGMAN REEF"),
    ("302", "ILHAS MACQUAIRE"),
    ("303", "ILHAS MARIANAS"),
    ("304", "ILHAS MARSHALL"),
    ("305", "ILHAS MACDONAL E HEARD"),
    ("306", "ILHAS NIUE"),
    ("307", "ILHAS NORFOLK"),
    ("308", "ILHAS PALAU"),
    ("309", "ILHAS SALOMAO"),
    ("310", "ILHAS TOKELAU"),
    ("311", "ILHAS WAKE"),
    ("312", "KALIMATAN"),
    ("313", "ILHAS LINHA"),
    ("314", "NAURU"),
    ("315", "ILHAS NOVA CALEDONIA"),
    ("316", "NOVA GUINE"),
    ("317", "NOVA ZELANDIA"),
    ("318", "ILHAS NOVAS HEBRIDAS"),
    ("319", "TERRITORIO DE PAPUA"),
    ("320", "ILHAS PASCOA"),
    ("321", "ILHAS PITCAIRIN"),
    ("322", "POLINESIA FRANCESA"),
    ("323", "SABAH"),
    ("324", "SAMOA AMERICANA"),
    ("325", "SAMOA OCIDENTAL"),
    ("326", "ILHAS SANTA CRUZ"),
    ("327", "SARAWAK"),
    ("328", "TERRITORIO DE COCOS"),
    ("329", "TIMOR"),
    ("330", "TONGA"),
    ("331", "TUVALU"),
    ("332", "ILHAS WALLIS E FUTUNA"),
    ("333", "ANTARTICO BRITANICO, TERRITORIO"),
    ("334", "ANTARTICA FRANCESA"),
    ("335", "TERR. ANTARTICO DA AUSTRALIA"),
    ("336", "ANTARTICO CHILENO"),
    ("337", "ANTARTICO ARGENTINO"),
    ("338", "ANTARTICO NORUEGUES"),
    ("339", "APATRIDA"),
    ("340", "DEPENDENCIA DE ROSS"),
    ("341", "TERRAS AUSTRAIS"),
    ("342", "BANGLADESH"),
    ("343", "CABO VERDE"),
    ("344", "GUINE BISSAU"),
    ("345", "IEMEN DO SUL"),
    ("346", "KARA KALPAK"),
    ("347", "ARMENIA"),
    ("348", "RUSSIA"),
    ("349", "SENEGAL"),
    ("350", "TANZANIA"),
]


RACAS: list[tuple[str, str]] = [
    ("1", "Branca"),
    ("2", "Preta"),
    ("3", "Parda"),
    ("4", "Amarela"),
    ("5", "Indígena"),
]


LOGRADOUROS: list[tuple[str, str]] = [
    ("645", "ACAMPAMENTO"),
    ("001", "ACESSO"),
    ("002", "ADRO"),
    ("501", "AEROPORTO"),
    ("004", "ALAMEDA"),
    ("005", "ALTO"),
    ("472", "AREA"),
    ("654", "AREA ESPECIAL"),
    ("465", "ARTERIA"),
    ("007", "ATALHO"),
    ("008", "AVENIDA"),
    ("651", "AVENIDA CONTORNO"),
    ("015", "BAIXA"),
    ("470", "BALAO"),
    ("009", "BALNEARIO"),
    ("011", "BECO"),
    ("010", "BELVEDERE"),
    ("012", "BLOCO"),
    ("013", "BOSQUE"),
    ("014", "BOULEVARD"),
    ("496", "BURACO"),
    ("016", "CAIS"),
    ("571", "CALCADA"),
    ("017", "CAMINHO"),
    ("023", "CAMPO"),
    ("495", "CANAL"),
    ("481", "CHACARA"),
    ("019", "CHAPADAO"),
    ("479", "CIRCULAR"),
    ("021", "COLONIA"),
    ("503", "COMPLEXO VIARIO"),
    ("485", "CONDOMINIO"),
    ("020", "CONJUNTO"),
    ("022", "CORREDOR"),
    ("024", "CORREGO"),
    ("478", "DESCIDA"),
    ("027", "DESVIO"),
    ("028", "DISTRITO"),
    ("468", "ELEVADA"),
    ("573", "ENTRADA PARTICULAR"),
    ("652", "ENTRE QUADRA"),
    ("030", "ESCADA"),
    ("474", "ESPLANADA"),
    ("032", "ESTACAO"),
    ("564", "ESTACIONAMENTO"),
    ("033", "ESTADIO"),
    ("498", "ESTANCIA"),
    ("031", "ESTRADA"),
    ("650", "ESTRADA MUNICIPAL"),
    ("036", "FAVELA"),
    ("037", "FAZENDA"),
    ("040", "FEIRA"),
    ("038", "FERROVIA"),
    ("039", "FONTE"),
    ("043", "FORTE"),
    ("045", "GALERIA"),
    ("046", "GRANJA"),
    ("486", "HABITACIONAL"),
    ("050", "ILHA"),
    ("052", "JARDIM"),
    ("473", "JARDINETE"),
    ("053", "LADEIRA"),
    ("499", "LAGO"),
    ("055", "LAGOA"),
    ("054", "LARGO"),
    ("056", "LOTEAMENTO"),
    ("477", "MARINA"),
    ("497", "MODULO"),
    ("060", "MONTE"),
    ("059", "MORRO"),
    ("500", "NUCLEO"),
    ("067", "PARADA"),
    ("471", "PARADOURO"),
    ("062", "PARALELA"),
    ("072", "PARQUE"),
    ("074", "PASSAGEM"),
    ("502", "PASSAGEM SUBTERRANEA"),
    ("073", "PASSARELA"),
    ("063", "PASSEIO"),
    ("064", "PATIO"),
    ("483", "PONTA"),
    ("076", "PONTE"),
    ("469", "PORTO"),
    ("065", "PRACA"),
    ("504", "PRACA DE ESPORTES"),
    ("070", "PRAIA"),
    ("071", "PROLONGAMENTO"),
    ("077", "QUADRA"),
    ("079", "QUINTA"),
    ("475", "QUINTAS"),
    ("082", "RAMAL"),
    ("482", "RAMPA"),
    ("087", "RECANTO"),
    ("487", "RESIDENCIAL"),
    ("089", "RETA"),
    ("088", "RETIRO"),
    ("091", "RETORNO"),
    ("569", "RODO ANEL"),
    ("090", "RODOVIA"),
    ("506", "ROTATORIA"),
    ("476", "ROTULA"),
    ("081", "RUA"),
    ("653", "RUA DE LIGACAO"),
    ("566", "RUA DE PEDESTRE"),
    ("094", "SERVIDAO"),
    ("095", "SETOR"),
    ("092", "SITIO"),
    ("096", "SUBIDA"),
    ("098", "TERMINAL"),
    ("100", "TRAVESSA"),
    ("570", "TRAVESSA PARTICULAR"),
    ("452", "TRECHO"),
    ("099", "TREVO"),
    ("097", "TRINCHEIRA"),
    ("567", "TUNEL"),
    ("480", "UNIDADE"),
    ("565", "VALA"),
    ("106", "VALE"),
    ("568", "VARIANTE"),
    ("453", "VEREDA"),
    ("101", "VIA"),
    ("572", "VIA DE ACESSO"),
    ("484", "VIA DE PEDESTRE"),
    ("505", "VIA ELEVADO"),
    ("646", "VIA EXPRESSA"),
    ("103", "VIADUTO"),
    ("105", "VIELA"),
    ("104", "VILA"),
    ("108", "ZIGUE-ZAGUE"),
]


def _create_table(name: str, codigo_len: int, descricao_len: int) -> None:
    op.create_table(
        name,
        sa.Column("id", UUIDType(), primary_key=True),
        sa.Column("codigo", sa.String(codigo_len), nullable=False),
        sa.Column("descricao", sa.String(descricao_len), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.UniqueConstraint("codigo", name=f"uq_{name}_codigo"),
        schema="app",
    )
    op.create_index(f"ix_{name}_active", name, ["active"], schema="app")


def _seed(name: str, rows: list[tuple[str, str]]) -> None:
    if not rows:
        return
    values = ",\n".join(
        f"    (gen_random_uuid(), '{cod}', $seed${desc}$seed$, true, true)"
        for cod, desc in rows
    )
    op.execute(f"""
        INSERT INTO app.{name} (id, codigo, descricao, is_system, active) VALUES
        {values}
    """)


def upgrade() -> None:
    _create_table("ref_nacionalidades", codigo_len=4, descricao_len=100)
    _create_table("ref_racas",           codigo_len=2, descricao_len=40)
    _create_table("ref_etnias",          codigo_len=4, descricao_len=100)
    _create_table("ref_logradouros",     codigo_len=4, descricao_len=50)

    _seed("ref_nacionalidades", NACIONALIDADES)
    _seed("ref_racas", RACAS)
    _seed("ref_logradouros", LOGRADOUROS)
    # ref_etnias: será preenchida quando receber os dados.


def downgrade() -> None:
    op.drop_index("ix_ref_logradouros_active", table_name="ref_logradouros", schema="app")
    op.drop_table("ref_logradouros", schema="app")
    op.drop_index("ix_ref_etnias_active", table_name="ref_etnias", schema="app")
    op.drop_table("ref_etnias", schema="app")
    op.drop_index("ix_ref_racas_active", table_name="ref_racas", schema="app")
    op.drop_table("ref_racas", schema="app")
    op.drop_index("ix_ref_nacionalidades_active", table_name="ref_nacionalidades", schema="app")
    op.drop_table("ref_nacionalidades", schema="app")
